FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
COPY ../ ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENV CONNECTION_STRING=""
ENV STATE_CACHE_TTL=""
ENV TRANSLATION_CACHE_TTL=""
ENTRYPOINT ["dotnet", "ParishForms.dll"]